### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by Remi-Tuy** [TrueLayer/truelayer-client-javascript-sample#2]
There is not example folder when git clone.
I assume it needs to be build, but there are no commands in your package.json to build the example.

Please some direction on how to build -> run this test app.

**Comment by mayankamencherla** [comment]
Hi @Remi-Tuy, Thanks for getting in touch with us. 
We are working on this and we will surely update you as soon as this is done.

**Comment by mayankamencherla** [comment]
@Remi-Tuy We have added better docs on the readme. So kindly let us know if you are facing any other issues with the code.
